#!/bin/sh

set -e

# Additional flags to pass to docker build
DOCKER_BUILD_FLAGS=$@

docker build -t windows-installer -f Dockerfile ${DOCKER_BUILD_FLAGS} .
CONTAINER="$(docker create -t -v $(pwd)/images:/images -v /var/run/docker.sock:/var/run/docker.sock windows-installer)"
docker start -i $CONTAINER
mkdir -p dist/
docker cp "${CONTAINER}:/installer/Output/." dist/
docker rm "${CONTAINER}" 2>/dev/null || true
