#!/bin/sh

set -e

docker build -t windows-installer -f Dockerfile.windows .
CONTAINER="$(docker create -t -v $(pwd)/images:/images -v /var/run/docker.sock:/var/run/docker.sock windows-installer)"
docker start -i $CONTAINER
mkdir -p dist/
docker cp "${CONTAINER}:/installer/Output/." dist/
docker rm "${CONTAINER}" 2>/dev/null || true
