#!/bin/bash

if [ -z "$SHELL" ]; then
    SHELL=bash
fi

env=$(which env)
cygstart=$(which cygstart)

subcyg_root=${1%/}
shift

# NOTE: Have to be *very* careful about quoting everything after the -c
# This does not yet cover all cases
$env -i $cygstart --wait ${subcyg_root}$SHELL -l -c '"'$@'"'
